name: CI

on: [push, pull_request]

jobs:
  #build-ubuntu:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: whatdf
  #    run: sudo apt-get install libcunit1
  #  - name: make
  #    run: gcc -std=c99 -Wall -D DEBUG -o runtest test/tests.c src/*.c -I$HOME/local/include -L$HOME/local/lib -lcunit -lprotobuf-c

  #build-windows:
  #  runs-on: ${{ matrix.os }}
  #  strategy:
  #    matrix:
  #      os: [windows-latest, windows-2016]
  #  steps:
  #  - uses: actions/checkout@v1
  #  - name: make
  #    run: make

  build-mac:
    runs-on: macos-latest
    steps:

# Install dependencies:
    - uses: actions/checkout@v1
    - name: install_cunit
      run: brew install cunit

# Clean and Build
    - name: clean
      run: make clean
    - name: build
      run: make build

# Run onnx backend unit tests (operators)
    - name: run_onnx_backend_tests
      run: make onnx_backend_tests

# Run end to end tests on some models (i.e. MNIST, tinyYOLO,...)
    - name: run_onnx_models_tests
      run: make onnx_models_tests
      
# Run some profiling/benchmarking on some models
    - name: run_benchmark # Get the time/cycles taken by each model
      run: make benchmark
    - name: run_valgrind  # Get % taken by each function
      run: make valgrind

# TODO: Memory leak checks, code coverage

# Parse the output with some python script. Ideas:
# - Display the benchmark of different models
#    - name: postprocess_data
#      run: xxx
